apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: assorted
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    path: charts/java-github-example-deploy
    repoURL: https://github.com/ploigos/java-github-example-ops.git
    targetRevision: main
    helm:
      parameters:
        - name: image.tag
          value: "quay.io/aagreen/java-github-example:1.0.2_c4f9c02"

  destination:
    namespace: fruits
    server: https://kubernetes.default.svc

  syncPolicy:

    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true

    retry:
      limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 15s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
