apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-runners
  namespace: devsecops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ploigos/openshift-actions-runner-chart
    path: ./
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: replicas
          value: "5"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: github-runners
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 15s
---
apiVersion: v1
data:
  token: cm9vdA==
kind: Secret
metadata:
  name: vault-secret
  namespace: github-runners
type: Opaque
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: github-runners
spec:
  provider:
    vault:
      server: "http://vault-internal.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-secret"
          key: "token"
---
