apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-runners-dotnet
  namespace: devsecops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ploigos/openshift-actions-runner-chart
    path: ./
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: replicas
          value: "5"
        - name: runnerTag
          value: "feature-dotnet-generate-metadata"
        - name: runnerLabels[0]
          value: "self-hosted"
        - name: runnerLabels[1]
          value: "python"
        - name: runnerLabels[2]
          value: "dotnet"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: github-runners-dotnet
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 15s
---

