apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/external-secrets-operator.openshift-operators: ""
  name: cert-manager-operator
  namespace: openshift-operators
spec:
  channel: tech-preview
  installPlanApproval: Manual
  name: cert-manager-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: cert-manager.v1.7.1